name: Webpage

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile-rust:
    runs-on: ubuntu-latest
    name: Compile Webpage
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - run: rustup target add wasm32-unknown-unknown
      - uses: oven-sh/setup-bun@v2
      - run: bun install -g wasm-pack
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-all-crates: true
          workspaces: './fibonacci-toy-rs-4-web -> target'
      - run: wasm-pack build --release
        working-directory: ./fibonacci-toy-rs-4-web
      - run: bun i
      - run: bun run build
      - name: Deploy Webpage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist/ --project-name=fibrs --commit-dirty=true
      